USE AdventureWorks;
GO

INSERT INTO NYSIIS_Replacements (Location, NGram, Replacement)
VALUES (N'End', N'DT', N'DD'),
	(N'End', N'EE', N'YY'),
	(N'End', N'IE', N'YY'),
	(N'End', N'ND', N'DD'),
	(N'End', N'NT', N'DD'),
	(N'End', N'RD', N'DD'),
	(N'End', N'RT', N'DD'),
	(N'Mid', N'A', N'A'),
	(N'Mid', N'E', N'A'),
	(N'Mid', N'I', N'A'),
	(N'Mid', N'K', N'C'),
	(N'Mid', N'M', N'N'),
	(N'Mid', N'O', N'A'),
	(N'Mid', N'Q', N'G'),
	(N'Mid', N'U', N'A'),
	(N'Mid', N'Z', N'S'),
	(N'Mid', N'AW', N'AA'),
	(N'Mid', N'EV', N'AF'),
	(N'Mid', N'EW', N'AA'),
	(N'Mid', N'IW', N'AA'),
	(N'Mid', N'KN', N'NN'),
	(N'Mid', N'OW', N'AA'),
	(N'Mid', N'PH', N'FF'),
	(N'Mid', N'UW', N'AA'),
	(N'Mid', N'SCH', N'SSS'),
	(N'Start', N'K', N'C'),
	(N'Start', N'KN', N'NN'),
	(N'Start', N'PF', N'FF'),
	(N'Start', N'PH', N'FF'),
	(N'Start', N'MAC', N'MCC'),
	(N'Start', N'SCH', N'SSS');
GO