//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: AdventureWorksModel.cs
// Generation date: 5/17/2008 9:10:55 PM
namespace AdventureWorksModel
{
    
    /// <summary>
    /// There are no comments for AdventureWorksEntities in the schema.
    /// </summary>
    public partial class AdventureWorksEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        public AdventureWorksEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Product> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<Product>("Product");
                }
                return this._Product;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Product;
        /// <summary>
        /// There are no comments for ProductPhoto in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<ProductPhoto> ProductPhoto
        {
            get
            {
                if ((this._ProductPhoto == null))
                {
                    this._ProductPhoto = base.CreateQuery<ProductPhoto>("ProductPhoto");
                }
                return this._ProductPhoto;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<ProductPhoto> _ProductPhoto;
        /// <summary>
        /// There are no comments for ProductProductPhoto in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<ProductProductPhoto> ProductProductPhoto
        {
            get
            {
                if ((this._ProductProductPhoto == null))
                {
                    this._ProductProductPhoto = base.CreateQuery<ProductProductPhoto>("ProductProductPhoto");
                }
                return this._ProductProductPhoto;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<ProductProductPhoto> _ProductProductPhoto;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
        /// <summary>
        /// There are no comments for ProductPhoto in the schema.
        /// </summary>
        public void AddToProductPhoto(ProductPhoto productPhoto)
        {
            base.AddObject("ProductPhoto", productPhoto);
        }
        /// <summary>
        /// There are no comments for ProductProductPhoto in the schema.
        /// </summary>
        public void AddToProductProductPhoto(ProductProductPhoto productProductPhoto)
        {
            base.AddObject("ProductProductPhoto", productProductPhoto);
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductID")]
    public partial class Product
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="productNumber">Initial value of ProductNumber.</param>
        /// <param name="makeFlag">Initial value of MakeFlag.</param>
        /// <param name="finishedGoodsFlag">Initial value of FinishedGoodsFlag.</param>
        /// <param name="safetyStockLevel">Initial value of SafetyStockLevel.</param>
        /// <param name="reorderPoint">Initial value of ReorderPoint.</param>
        /// <param name="standardCost">Initial value of StandardCost.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="daysToManufacture">Initial value of DaysToManufacture.</param>
        /// <param name="sellStartDate">Initial value of SellStartDate.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Product CreateProduct(int productID, string name, string productNumber, bool makeFlag, bool finishedGoodsFlag, short safetyStockLevel, short reorderPoint, decimal standardCost, decimal listPrice, int daysToManufacture, global::System.DateTime sellStartDate, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.Name = name;
            product.ProductNumber = productNumber;
            product.MakeFlag = makeFlag;
            product.FinishedGoodsFlag = finishedGoodsFlag;
            product.SafetyStockLevel = safetyStockLevel;
            product.ReorderPoint = reorderPoint;
            product.StandardCost = standardCost;
            product.ListPrice = listPrice;
            product.DaysToManufacture = daysToManufacture;
            product.SellStartDate = sellStartDate;
            product.rowguid = rowguid;
            product.ModifiedDate = modifiedDate;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ProductNumber in the schema.
        /// </summary>
        public string ProductNumber
        {
            get
            {
                return this._ProductNumber;
            }
            set
            {
                this.OnProductNumberChanging(value);
                this._ProductNumber = value;
                this.OnProductNumberChanged();
            }
        }
        private string _ProductNumber;
        partial void OnProductNumberChanging(string value);
        partial void OnProductNumberChanged();
        /// <summary>
        /// There are no comments for Property MakeFlag in the schema.
        /// </summary>
        public bool MakeFlag
        {
            get
            {
                return this._MakeFlag;
            }
            set
            {
                this.OnMakeFlagChanging(value);
                this._MakeFlag = value;
                this.OnMakeFlagChanged();
            }
        }
        private bool _MakeFlag;
        partial void OnMakeFlagChanging(bool value);
        partial void OnMakeFlagChanged();
        /// <summary>
        /// There are no comments for Property FinishedGoodsFlag in the schema.
        /// </summary>
        public bool FinishedGoodsFlag
        {
            get
            {
                return this._FinishedGoodsFlag;
            }
            set
            {
                this.OnFinishedGoodsFlagChanging(value);
                this._FinishedGoodsFlag = value;
                this.OnFinishedGoodsFlagChanged();
            }
        }
        private bool _FinishedGoodsFlag;
        partial void OnFinishedGoodsFlagChanging(bool value);
        partial void OnFinishedGoodsFlagChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        public string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
            }
        }
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property SafetyStockLevel in the schema.
        /// </summary>
        public short SafetyStockLevel
        {
            get
            {
                return this._SafetyStockLevel;
            }
            set
            {
                this.OnSafetyStockLevelChanging(value);
                this._SafetyStockLevel = value;
                this.OnSafetyStockLevelChanged();
            }
        }
        private short _SafetyStockLevel;
        partial void OnSafetyStockLevelChanging(short value);
        partial void OnSafetyStockLevelChanged();
        /// <summary>
        /// There are no comments for Property ReorderPoint in the schema.
        /// </summary>
        public short ReorderPoint
        {
            get
            {
                return this._ReorderPoint;
            }
            set
            {
                this.OnReorderPointChanging(value);
                this._ReorderPoint = value;
                this.OnReorderPointChanged();
            }
        }
        private short _ReorderPoint;
        partial void OnReorderPointChanging(short value);
        partial void OnReorderPointChanged();
        /// <summary>
        /// There are no comments for Property StandardCost in the schema.
        /// </summary>
        public decimal StandardCost
        {
            get
            {
                return this._StandardCost;
            }
            set
            {
                this.OnStandardCostChanging(value);
                this._StandardCost = value;
                this.OnStandardCostChanged();
            }
        }
        private decimal _StandardCost;
        partial void OnStandardCostChanging(decimal value);
        partial void OnStandardCostChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        public decimal ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this._ListPrice = value;
                this.OnListPriceChanged();
            }
        }
        private decimal _ListPrice;
        partial void OnListPriceChanging(decimal value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        public string Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
            }
        }
        private string _Size;
        partial void OnSizeChanging(string value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property SizeUnitMeasureCode in the schema.
        /// </summary>
        public string SizeUnitMeasureCode
        {
            get
            {
                return this._SizeUnitMeasureCode;
            }
            set
            {
                this.OnSizeUnitMeasureCodeChanging(value);
                this._SizeUnitMeasureCode = value;
                this.OnSizeUnitMeasureCodeChanged();
            }
        }
        private string _SizeUnitMeasureCode;
        partial void OnSizeUnitMeasureCodeChanging(string value);
        partial void OnSizeUnitMeasureCodeChanged();
        /// <summary>
        /// There are no comments for Property WeightUnitMeasureCode in the schema.
        /// </summary>
        public string WeightUnitMeasureCode
        {
            get
            {
                return this._WeightUnitMeasureCode;
            }
            set
            {
                this.OnWeightUnitMeasureCodeChanging(value);
                this._WeightUnitMeasureCode = value;
                this.OnWeightUnitMeasureCodeChanged();
            }
        }
        private string _WeightUnitMeasureCode;
        partial void OnWeightUnitMeasureCodeChanging(string value);
        partial void OnWeightUnitMeasureCodeChanged();
        /// <summary>
        /// There are no comments for Property Weight in the schema.
        /// </summary>
        public global::System.Nullable<decimal> Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this.OnWeightChanging(value);
                this._Weight = value;
                this.OnWeightChanged();
            }
        }
        private global::System.Nullable<decimal> _Weight;
        partial void OnWeightChanging(global::System.Nullable<decimal> value);
        partial void OnWeightChanged();
        /// <summary>
        /// There are no comments for Property DaysToManufacture in the schema.
        /// </summary>
        public int DaysToManufacture
        {
            get
            {
                return this._DaysToManufacture;
            }
            set
            {
                this.OnDaysToManufactureChanging(value);
                this._DaysToManufacture = value;
                this.OnDaysToManufactureChanged();
            }
        }
        private int _DaysToManufacture;
        partial void OnDaysToManufactureChanging(int value);
        partial void OnDaysToManufactureChanged();
        /// <summary>
        /// There are no comments for Property ProductLine in the schema.
        /// </summary>
        public string ProductLine
        {
            get
            {
                return this._ProductLine;
            }
            set
            {
                this.OnProductLineChanging(value);
                this._ProductLine = value;
                this.OnProductLineChanged();
            }
        }
        private string _ProductLine;
        partial void OnProductLineChanging(string value);
        partial void OnProductLineChanged();
        /// <summary>
        /// There are no comments for Property Class in the schema.
        /// </summary>
        public string Class
        {
            get
            {
                return this._Class;
            }
            set
            {
                this.OnClassChanging(value);
                this._Class = value;
                this.OnClassChanged();
            }
        }
        private string _Class;
        partial void OnClassChanging(string value);
        partial void OnClassChanged();
        /// <summary>
        /// There are no comments for Property Style in the schema.
        /// </summary>
        public string Style
        {
            get
            {
                return this._Style;
            }
            set
            {
                this.OnStyleChanging(value);
                this._Style = value;
                this.OnStyleChanged();
            }
        }
        private string _Style;
        partial void OnStyleChanging(string value);
        partial void OnStyleChanged();
        /// <summary>
        /// There are no comments for Property ProductSubcategoryID in the schema.
        /// </summary>
        public global::System.Nullable<int> ProductSubcategoryID
        {
            get
            {
                return this._ProductSubcategoryID;
            }
            set
            {
                this.OnProductSubcategoryIDChanging(value);
                this._ProductSubcategoryID = value;
                this.OnProductSubcategoryIDChanged();
            }
        }
        private global::System.Nullable<int> _ProductSubcategoryID;
        partial void OnProductSubcategoryIDChanging(global::System.Nullable<int> value);
        partial void OnProductSubcategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ProductModelID in the schema.
        /// </summary>
        public global::System.Nullable<int> ProductModelID
        {
            get
            {
                return this._ProductModelID;
            }
            set
            {
                this.OnProductModelIDChanging(value);
                this._ProductModelID = value;
                this.OnProductModelIDChanged();
            }
        }
        private global::System.Nullable<int> _ProductModelID;
        partial void OnProductModelIDChanging(global::System.Nullable<int> value);
        partial void OnProductModelIDChanged();
        /// <summary>
        /// There are no comments for Property SellStartDate in the schema.
        /// </summary>
        public global::System.DateTime SellStartDate
        {
            get
            {
                return this._SellStartDate;
            }
            set
            {
                this.OnSellStartDateChanging(value);
                this._SellStartDate = value;
                this.OnSellStartDateChanged();
            }
        }
        private global::System.DateTime _SellStartDate;
        partial void OnSellStartDateChanging(global::System.DateTime value);
        partial void OnSellStartDateChanged();
        /// <summary>
        /// There are no comments for Property SellEndDate in the schema.
        /// </summary>
        public global::System.Nullable<global::System.DateTime> SellEndDate
        {
            get
            {
                return this._SellEndDate;
            }
            set
            {
                this.OnSellEndDateChanging(value);
                this._SellEndDate = value;
                this.OnSellEndDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _SellEndDate;
        partial void OnSellEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnSellEndDateChanged();
        /// <summary>
        /// There are no comments for Property DiscontinuedDate in the schema.
        /// </summary>
        public global::System.Nullable<global::System.DateTime> DiscontinuedDate
        {
            get
            {
                return this._DiscontinuedDate;
            }
            set
            {
                this.OnDiscontinuedDateChanging(value);
                this._DiscontinuedDate = value;
                this.OnDiscontinuedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DiscontinuedDate;
        partial void OnDiscontinuedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDiscontinuedDateChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for ProductProductPhoto in the schema.
        /// </summary>
        public global::System.Collections.ObjectModel.Collection<ProductProductPhoto> ProductProductPhoto
        {
            get
            {
                return this._ProductProductPhoto;
            }
        }
        private global::System.Collections.ObjectModel.Collection<ProductProductPhoto> _ProductProductPhoto = new global::System.Collections.ObjectModel.Collection<ProductProductPhoto>();
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.ProductProductPhoto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// ProductPhotoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductID", "ProductPhotoID")]
    public partial class ProductProductPhoto
    {
        /// <summary>
        /// Create a new ProductProductPhoto object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productPhotoID">Initial value of ProductPhotoID.</param>
        /// <param name="primary">Initial value of Primary.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static ProductProductPhoto CreateProductProductPhoto(int productID, int productPhotoID, bool primary, global::System.DateTime modifiedDate)
        {
            ProductProductPhoto productProductPhoto = new ProductProductPhoto();
            productProductPhoto.ProductID = productID;
            productProductPhoto.ProductPhotoID = productPhotoID;
            productProductPhoto.Primary = primary;
            productProductPhoto.ModifiedDate = modifiedDate;
            return productProductPhoto;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductPhotoID in the schema.
        /// </summary>
        public int ProductPhotoID
        {
            get
            {
                return this._ProductPhotoID;
            }
            set
            {
                this.OnProductPhotoIDChanging(value);
                this._ProductPhotoID = value;
                this.OnProductPhotoIDChanged();
            }
        }
        private int _ProductPhotoID;
        partial void OnProductPhotoIDChanging(int value);
        partial void OnProductPhotoIDChanged();
        /// <summary>
        /// There are no comments for Property Primary in the schema.
        /// </summary>
        public bool Primary
        {
            get
            {
                return this._Primary;
            }
            set
            {
                this.OnPrimaryChanging(value);
                this._Primary = value;
                this.OnPrimaryChanged();
            }
        }
        private bool _Primary;
        partial void OnPrimaryChanging(bool value);
        partial void OnPrimaryChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public Product Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
            }
        }
        private Product _Product;
        /// <summary>
        /// There are no comments for ProductPhoto in the schema.
        /// </summary>
        public ProductPhoto ProductPhoto
        {
            get
            {
                return this._ProductPhoto;
            }
            set
            {
                this._ProductPhoto = value;
            }
        }
        private ProductPhoto _ProductPhoto;
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.ProductPhoto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductPhotoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductPhotoID")]
    public partial class ProductPhoto
    {
        /// <summary>
        /// Create a new ProductPhoto object.
        /// </summary>
        /// <param name="productPhotoID">Initial value of ProductPhotoID.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static ProductPhoto CreateProductPhoto(int productPhotoID, global::System.DateTime modifiedDate)
        {
            ProductPhoto productPhoto = new ProductPhoto();
            productPhoto.ProductPhotoID = productPhotoID;
            productPhoto.ModifiedDate = modifiedDate;
            return productPhoto;
        }
        /// <summary>
        /// There are no comments for Property ProductPhotoID in the schema.
        /// </summary>
        public int ProductPhotoID
        {
            get
            {
                return this._ProductPhotoID;
            }
            set
            {
                this.OnProductPhotoIDChanging(value);
                this._ProductPhotoID = value;
                this.OnProductPhotoIDChanged();
            }
        }
        private int _ProductPhotoID;
        partial void OnProductPhotoIDChanging(int value);
        partial void OnProductPhotoIDChanged();
        /// <summary>
        /// There are no comments for Property ThumbNailPhoto in the schema.
        /// </summary>
        public byte[] ThumbNailPhoto
        {
            get
            {
                if ((this._ThumbNailPhoto != null))
                {
                    return ((byte[])(this._ThumbNailPhoto.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnThumbNailPhotoChanging(value);
                this._ThumbNailPhoto = value;
                this.OnThumbNailPhotoChanged();
            }
        }
        private byte[] _ThumbNailPhoto;
        partial void OnThumbNailPhotoChanging(byte[] value);
        partial void OnThumbNailPhotoChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailPhotoFileName in the schema.
        /// </summary>
        public string ThumbnailPhotoFileName
        {
            get
            {
                return this._ThumbnailPhotoFileName;
            }
            set
            {
                this.OnThumbnailPhotoFileNameChanging(value);
                this._ThumbnailPhotoFileName = value;
                this.OnThumbnailPhotoFileNameChanged();
            }
        }
        private string _ThumbnailPhotoFileName;
        partial void OnThumbnailPhotoFileNameChanging(string value);
        partial void OnThumbnailPhotoFileNameChanged();
        /// <summary>
        /// There are no comments for Property LargePhoto in the schema.
        /// </summary>
        public byte[] LargePhoto
        {
            get
            {
                if ((this._LargePhoto != null))
                {
                    return ((byte[])(this._LargePhoto.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnLargePhotoChanging(value);
                this._LargePhoto = value;
                this.OnLargePhotoChanged();
            }
        }
        private byte[] _LargePhoto;
        partial void OnLargePhotoChanging(byte[] value);
        partial void OnLargePhotoChanged();
        /// <summary>
        /// There are no comments for Property LargePhotoFileName in the schema.
        /// </summary>
        public string LargePhotoFileName
        {
            get
            {
                return this._LargePhotoFileName;
            }
            set
            {
                this.OnLargePhotoFileNameChanging(value);
                this._LargePhotoFileName = value;
                this.OnLargePhotoFileNameChanged();
            }
        }
        private string _LargePhotoFileName;
        partial void OnLargePhotoFileNameChanging(string value);
        partial void OnLargePhotoFileNameChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for ProductProductPhoto in the schema.
        /// </summary>
        public global::System.Collections.ObjectModel.Collection<ProductProductPhoto> ProductProductPhoto
        {
            get
            {
                return this._ProductProductPhoto;
            }
        }
        private global::System.Collections.ObjectModel.Collection<ProductProductPhoto> _ProductProductPhoto = new global::System.Collections.ObjectModel.Collection<ProductProductPhoto>();
    }
}
