//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.Examples.AdvPersonSearchService {
    using System.Data;
    using System.Data.SqlTypes;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AdvPersonSearchService.AdvPersonSearchSoap")]
    public interface AdvPersonSearchSoap {
        
        // CODEGEN: Parameter 'LastName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.orgSearchByLastName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapOut SearchByLastName(Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByLastName", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class s0MsgSearchByLastNameSoapIn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.SqlTypes.SqlString LastName;
        
        public s0MsgSearchByLastNameSoapIn() {
        }
        
        public s0MsgSearchByLastNameSoapIn(System.Data.SqlTypes.SqlString LastName) {
            this.LastName = LastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByLastNameResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class s0MsgSearchByLastNameSoapOut {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Data.DataSet SearchByLastNameResult;
        
        public s0MsgSearchByLastNameSoapOut() {
        }
        
        public s0MsgSearchByLastNameSoapOut(System.Data.DataSet SearchByLastNameResult) {
            this.SearchByLastNameResult = SearchByLastNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AdvPersonSearchSoapChannel : Apress.Examples.AdvPersonSearchService.AdvPersonSearchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AdvPersonSearchSoapClient : System.ServiceModel.ClientBase<Apress.Examples.AdvPersonSearchService.AdvPersonSearchSoap>, Apress.Examples.AdvPersonSearchService.AdvPersonSearchSoap {
        
        public AdvPersonSearchSoapClient() {
        }
        
        public AdvPersonSearchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvPersonSearchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvPersonSearchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvPersonSearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapOut Apress.Examples.AdvPersonSearchService.AdvPersonSearchSoap.SearchByLastName(Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapIn request) {
            return base.Channel.SearchByLastName(request);
        }
        
        public System.Data.DataSet SearchByLastName(System.Data.SqlTypes.SqlString LastName) {
            Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapIn inValue = new Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapIn();
            inValue.LastName = LastName;
            Apress.Examples.AdvPersonSearchService.s0MsgSearchByLastNameSoapOut retVal = ((Apress.Examples.AdvPersonSearchService.AdvPersonSearchSoap)(this)).SearchByLastName(inValue);
            return retVal.SearchByLastNameResult;
        }
    }
}
